baseURL = "https://keishasperkins.com/"
languageCode = "en-us"
title = "Keisha S Perkins"
copyright = "Keisha S Perkins"
googleAnalytics = "UA-88471731-1"
publishDir = "docs"
disqusShortname = "keishasperkins"

[Params]
	headline = "Keisha S Perkins"
	description = "is a designer and a developer"

[Author]
    name = "Keisha S Perkins"
